### ISSUE TITLE
虚拟机网络问题-静态ip配置

### ISSUE THREAD

**Issue by lam-guo** [lam-guo/water_essay#4]
#虚拟机使用踩坑经历
```
虚拟机版本：vmware fusion macos
操作系统：ubuntu server 20.04.2
```

##虚拟机网络问题

###静态ip配置
**起因**: 虚拟机安装了**kubesphere**,重启虚拟机后无法重启**kubesphere**
**经过**: 排查发现**docker**中的**etcd**无法启动,查看日志发现是**ip地址无法绑定**,是因为重启后ubuntu的ip地址发生了改变。
**方案**:

 - **A方案**修改**ubuntu**的ip为之前的地址,并且静态。
 - **B方案**修改**etcd**相关配置。

综合考虑**A方案**应该更为简单

----------

**步骤**：

 1. mac系统 >> 网络偏好设置 >> TCP/IP >> dhcp选择**手动模式**并配置ip地址
 2. ubuntu系统 修改 **/etc/netplan**下的**ymal**文件(我的为00-installer-config.yaml)。如下
```
network:
  ethernets:
    ens33:  #你的网卡
            addresses: [172.16.1.174/22] #配置你想要的静态ip，要检查有否冲突，掩码位数需要计算
            gateway4: 172.16.0.1 #网关地址
            nameservers:
                    addresses: [202.96.128.86, 114.114.114.114] #配置dns，不然无法访问外网
  version: 2
```
 3. 执行**netplan apply**,检查**ifconfig**,检查能否**ping**内部以及外部网络
